spring:
  profiles:
    active: native
---
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          search-locations:
            file:///repo/spring-boot-examples/spring-boot-microservices/spring-boot-service-config-properties/{application}/{profile},
            file:///repo/spring-boot-examples/spring-boot-microservices/spring-boot-service-config-properties/global/{profile}
---
spring:
  profiles: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/isilona/microservices/
          search-paths:
            - "ms-config-properties/{application}/{profile}"
            - "ms-config-properties/global/{profile}"

